import type { Metadata } from "next";
// import { Inter, Space_Grotesk } from "next/font/google";
import Authprovider from "./components/authprovider/authprovider";
import { Providers } from "./providers";
import "./globals.css";
import AuthNavbar from "./components/AuthNavbar";
import {inter, space_grotesk} from "./fonts";
// const inter = Inter({ subsets: ["latin"] });

// const space_grotesk = Space_Grotesk({
//   weight: ['400', '500', '700'],
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-space-grotesk'
// });
export const metadata: Metadata = {
  title: "Vital Web App",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.className} ${space_grotesk.variable}`}>
        <Providers>
          
          <Authprovider>
            <AuthNavbar />
            {children}
            </Authprovider>
        </Providers>
      </body>
    </html>
  );
}
